KL-292 Create K8s manifest for Chief Onboarding
kuberlogic/chiefonboarding-operator pull request #1
Opened 2022-04-06 07:43 UTC by geodome

2022-04-06 08:45 UTC, telepenin commented
Could you use [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) for skeleton of file structure?

2022-04-11 07:30 UTC, ynnt requested changes

2022-04-11 07:30 UTC, ynnt commented on docker-compose.yml
> +version: '3'
This docker-compose file will not work

2022-04-11 07:30 UTC, ynnt commented on manifest/nuxt-deployment.yaml
> +      - args:
The container will not start

2022-04-11 07:30 UTC, ynnt commented on manifest/web-deployment.yaml
> +        image: web
How will it work?

2022-04-11 07:37 UTC, geodome commented on docker-compose.yml
> +version: '3'
This docker-compose file is not part of the k8s manifest. It originated from the chief-onboarding repo.

2022-04-14 08:37 UTC, geodome commented
@ynnt 

I have updated the manifests.
- chiefonboarding-app.yaml defines the deployment manifest
- chiefonboarding-service.yaml defines the service manifest
- configmap.yaml contains the Caddyfile for the caddy proxy used by the chiefonboarding-app.
- chiefonboarding-db.yaml defines the deployment manifest for the postgres databased used by the chiefonboarding app.
- chiefonboarding-service.yaml defines the service manifest for the postgres db.

2022-04-19 07:35 UTC, ynnt approved these changes

2022-04-19 08:18 UTC, merged